#!/usr/bin/env python3
"""Wrap the artifact-style page fragment in a standalone HTML document.

The fragment (web/pad.body.html) carries only <title>, <style>, markup and
<script>, because the claude.ai artifact host supplies the skeleton itself.
A normal web server supplies nothing, so this adds the parts that matter:
the viewport meta (without it a phone renders at 980px and every mobile
media query is skipped), cache directives, and a build stamp.
"""
import datetime, json, pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
frag = (root / "web" / "pad.body.html").read_text()
# the fragment opens with <title>/<link>/<style>; those belong in <head>,
# everything after the last </style> is body content
split = frag.rindex("</style>") + len("</style>")
frag_head, frag_body = frag[:split], frag[split:]
build = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

doc = f"""<!doctype html>
<html lang="en" data-build="{build}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#0d1012" media="(prefers-color-scheme: dark)">
<meta name="theme-color" content="#f2f3f1" media="(prefers-color-scheme: light)">
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
<meta name="description" content="Take a picture, keep the pad. One photo becomes one sustained chord you can export as a loop, a one-shot and MIDI.">
<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" href="icons/favicon-64.png" sizes="64x64">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Pad">
<meta name="application-name" content="Pad">
<style>
  *{{box-sizing:border-box;}}
  html,body{{margin:0;}}
  :root{{padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px);}}
  img{{max-width:100%;}}
  [hidden]{{display:none!important;}}
</style>
{frag_head}
</head>
<body>
{frag_body}
</body>
</html>
"""
(root / "index.html").write_text(doc)

# --- tuning lab (plain page, not part of the installed app) ---------------
lab = (root / "web" / "lab.body.html").read_text()
lsplit = lab.rindex("</style>") + len("</style>")
(root / "lab.html").write_text(f"""<!doctype html>
<html lang="en" data-build="{build}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta name="robots" content="noindex">
<link rel="icon" href="icons/favicon-64.png" sizes="64x64">
<style>*{{box-sizing:border-box;}} html,body{{margin:0;}} [hidden]{{display:none!important;}}</style>
{lab[:lsplit]}
</head>
<body>
{lab[lsplit:]}
</body>
</html>
""")

# --- PWA manifest ---------------------------------------------------------
manifest = {
    "name": "Pad From Picture",
    "short_name": "Pad",
    "description": "Take a picture, keep the pad.",
    "start_url": "./?src=app",
    "scope": "./",
    "display": "standalone",
    "orientation": "portrait",
    "background_color": "#0d1012",
    "theme_color": "#0d1012",
    "icons": [
        {"src": "icons/icon-192.png", "sizes": "192x192", "type": "image/png"},
        {"src": "icons/icon-512.png", "sizes": "512x512", "type": "image/png"},
        {"src": "icons/icon-maskable-512.png", "sizes": "512x512",
         "type": "image/png", "purpose": "maskable"},
    ],
}
(root / "manifest.webmanifest").write_text(json.dumps(manifest, indent=2))

# --- service worker -------------------------------------------------------
# Network-first for the page so a new build is picked up on the next load, with
# a cached copy as the offline fallback. The cache name carries the build stamp,
# so old caches are dropped on activate rather than lingering.
sw = f"""/* generated by tools/build.py — do not edit */
const CACHE = "pad-{build.replace(' ', '-').replace(':', '')}";
const SHELL = ["./", "./index.html", "./manifest.webmanifest",
  "./icons/icon-192.png", "./icons/icon-512.png",
  "./icons/icon-maskable-512.png", "./icons/apple-touch-icon.png"];

self.addEventListener("install", e => {{
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
}});

self.addEventListener("activate", e => {{
  e.waitUntil(caches.keys()
    .then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
}});

self.addEventListener("fetch", e => {{
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;      // fonts etc. go straight to the network
  e.respondWith(
    fetch(req)
      .then(res => {{
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {{}});
        return res;
      }})
      .catch(() => caches.match(req).then(hit => hit || caches.match("./index.html")))
  );
}});
"""
(root / "sw.js").write_text(sw)

print(f"built index.html  ({len(doc)} bytes, build {build})")
print("built manifest.webmanifest + sw.js")
